runtime: custom
env: flex

entrypoint: gunicorn -b :$PORT app:app

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.65

env_variables:
  FLASK_ENV: production
  SECRET_KEY: your_secret_key  # Replace with a secure key
